// export const navLinks = [
//   { name: 'Home', href: '/' },
//   { name: 'About Us', href: '/about' },
//   { name: 'Courses', href: '/courses' },
//   { name: 'Gallery', href: '/gallery' },
//   { name: 'Blogs', href: '/blogs' },
//   { name: 'Contact Us', href: '/contact' },
// ];

// export const stats = [
//   { value: '500+', label: 'Students Trained' },
//   { value: '4+', label: 'Professional Courses' },
//   { value: '100+', label: 'Practical Labs' },
//   { value: '24/7', label: 'Learning Support' },
// ];

// export const courses = [
//   {
//     id: 'networking',
//     slug: 'networking',
//     title: 'Networking',
//     category: 'Networking',
//     description: 'Build strong networking fundamentals and understand how modern networks operate.',
//     longDescription: 'Comprehensive networking course covering OSI model, TCP/IP, subnetting, routing, switching, and network troubleshooting with hands-on labs.',
//     icon: '🌐',
//     level: 'Beginner',
//     duration: '6 weeks',
//     lessons: 12,
//     certificate: true,
//   },
//   {
//     id: 'ccna',
//     slug: 'ccna',
//     title: 'CCNA',
//     category: 'CCNA',
//     description: 'Learn Cisco networking concepts, routing, switching, network security and practical configurations.',
//     longDescription: 'Complete CCNA training with hands-on labs, real-world scenarios, and exam preparation for Cisco certification.',
//     icon: '🔧',
//     level: 'Intermediate',
//     duration: '8 weeks',
//     lessons: 18,
//     certificate: true,
//   },
//   {
//     id: 'mcsa',
//     slug: 'mcsa',
//     title: 'MCSA',
//     category: 'MCSA',
//     description: 'Develop professional-level knowledge of Microsoft server and infrastructure technologies.',
//     longDescription: 'Microsoft Certified Solutions Associate training covering Windows Server, Active Directory, and infrastructure management.',
//     icon: '💻',
//     level: 'Advanced',
//     duration: '10 weeks',
//     lessons: 20,
//     certificate: true,
//   },
//   {
//     id: 'cyber-security',
//     slug: 'cyber-security',
//     title: 'Cyber Security',
//     category: 'Cyber Security',
//     description: 'Learn cybersecurity fundamentals, ethical hacking concepts, vulnerability assessment, and defensive security.',
//     longDescription: 'Comprehensive cybersecurity training covering ethical hacking, network security, vulnerability assessment, and defensive strategies.',
//     icon: '🔒',
//     level: 'Intermediate',
//     duration: '12 weeks',
//     lessons: 24,
//     certificate: true,
//   },
// ];

// export const features = [
//   'Practical Learning',
//   'Industry-Focused Curriculum',
//   'Hands-on Labs',
//   'Career-Oriented Training',
//   'Expert Guidance',
//   'Certification Support',
// ];

// export const blogPosts = [
//   {
//     id: 1,
//     slug: 'what-is-cybersecurity',
//     title: 'What is Cybersecurity?',
//     category: 'Cybersecurity',
//     excerpt: 'Learn the fundamentals of cybersecurity and why it matters in today\'s digital world. Discover how to protect yourself and your organization.',
//     author: 'Admin',
//     date: '2026-01-15',
//     readTime: '5 min read',
//   },
//   {
//     id: 2,
//     slug: 'how-to-start-career-in-cybersecurity',
//     title: 'How to Start a Career in Cybersecurity',
//     category: 'Career',
//     excerpt: 'A step-by-step guide to building a successful career in cybersecurity. Learn about required skills, certifications, and job opportunities.',
//     author: 'Admin',
//     date: '2026-01-20',
//     readTime: '7 min read',
//   },
//   {
//     id: 3,
//     slug: 'ccna-vs-cybersecurity',
//     title: 'CCNA vs Cybersecurity',
//     category: 'Comparison',
//     excerpt: 'Understanding the differences between CCNA and Cybersecurity career paths. Which one is right for you?',
//     author: 'Admin',
//     date: '2026-01-25',
//     readTime: '6 min read',
//   },
//   {
//     id: 4,
//     slug: 'what-is-ethical-hacking',
//     title: 'What is Ethical Hacking?',
//     category: 'Ethical Hacking',
//     excerpt: 'Explore the world of ethical hacking and how it helps organizations protect their digital assets from cyber threats.',
//     author: 'Admin',
//     date: '2026-02-01',
//     readTime: '8 min read',
//   },
//   {
//     id: 5,
//     slug: 'networking-fundamentals',
//     title: 'Networking Fundamentals',
//     category: 'Networking',
//     excerpt: 'Master the basics of computer networking including protocols, topologies, and essential concepts for IT professionals.',
//     author: 'Admin',
//     date: '2026-02-05',
//     readTime: '6 min read',
//   },
//   {
//     id: 6,
//     slug: 'common-cybersecurity-threats',
//     title: 'Common Cybersecurity Threats',
//     category: 'Threats',
//     excerpt: 'Learn about the most common cybersecurity threats facing organizations today and how to defend against them.',
//     author: 'Admin',
//     date: '2026-02-10',
//     readTime: '5 min read',
//   },
// ];



export const stats = [
  { value: '500+', label: 'Students Trained' },
  { value: '4+', label: 'Professional Courses' },
  { value: '100+', label: 'Practical Labs' },
  { value: '24/7', label: 'Learning Support' },
];

export const courses = [
  {
    id: 'networking',
    slug: 'networking',
    title: 'Networking',
    category: 'Networking',
    description: 'Build strong networking fundamentals and understand how modern networks operate.',
    longDescription: 'Comprehensive networking course covering OSI model, TCP/IP, subnetting, routing, switching, and network troubleshooting with hands-on labs.',
    icon: '🌐',
    level: 'Beginner',
    duration: '6 weeks',
    lessons: 12,
    certificate: true,
    curriculum: [
      'Introduction to Networking',
      'OSI Model and TCP/IP',
      'IP Addressing and Subnetting',
      'Routing Fundamentals',
      'Switching and VLANs',
      'Network Troubleshooting',
    ],
  },
  {
    id: 'ccna',
    slug: 'ccna',
    title: 'CCNA',
    category: 'CCNA',
    description: 'Learn Cisco networking concepts, routing, switching, network security and practical configurations.',
    longDescription: 'Complete CCNA training with hands-on labs, real-world scenarios, and exam preparation for Cisco certification.',
    icon: '🔧',
    level: 'Intermediate',
    duration: '8 weeks',
    lessons: 18,
    certificate: true,
    curriculum: [
      'Cisco IOS Fundamentals',
      'Routing Protocols (OSPF, EIGRP)',
      'Switching and STP',
      'Network Security Fundamentals',
      'WAN Technologies',
      'CCNA Exam Preparation',
    ],
  },
  {
    id: 'mcsa',
    slug: 'mcsa',
    title: 'MCSA',
    category: 'MCSA',
    description: 'Develop professional-level knowledge of Microsoft server and infrastructure technologies.',
    longDescription: 'Microsoft Certified Solutions Associate training covering Windows Server, Active Directory, and infrastructure management.',
    icon: '💻',
    level: 'Advanced',
    duration: '10 weeks',
    lessons: 20,
    certificate: true,
    curriculum: [
      'Windows Server Installation',
      'Active Directory Services',
      'DNS and DHCP Configuration',
      'Group Policy Management',
      'Server Security',
      'MCSA Exam Preparation',
    ],
  },
  {
    id: 'cyber-security',
    slug: 'cyber-security',
    title: 'Cyber Security',
    category: 'Cyber Security',
    description: 'Learn cybersecurity fundamentals, ethical hacking concepts, vulnerability assessment, and defensive security.',
    longDescription: 'Comprehensive cybersecurity training covering ethical hacking, network security, vulnerability assessment, and defensive strategies.',
    icon: '🔒',
    level: 'Intermediate',
    duration: '12 weeks',
    lessons: 24,
    certificate: true,
    curriculum: [
      'Cybersecurity Fundamentals',
      'Network Security',
      'Ethical Hacking Concepts',
      'Vulnerability Assessment',
      'Security Tools',
      'Threat Detection and Response',
      'Defensive Security',
      'Security Best Practices',
    ],
  },
];

export const features = [
  'Practical Learning',
  'Industry-Focused Curriculum',
  'Hands-on Labs',
  'Career-Oriented Training',
  'Expert Guidance',
  'Certification Support',
];

export const blogPosts = [
  {
    id: 1,
    slug: 'what-is-cybersecurity',
    title: 'What is Cybersecurity?',
    category: 'Cybersecurity',
    excerpt: 'Learn the fundamentals of cybersecurity and why it matters in today\'s digital world.',
    author: 'Admin',
    date: '2026-01-15',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=500&fit=crop&q=80',
  },
  {
    id: 2,
    slug: 'how-to-start-career-in-cybersecurity',
    title: 'How to Start a Career in Cybersecurity',
    category: 'Career',
    excerpt: 'A step-by-step guide to building a successful career in cybersecurity.',
    author: 'Admin',
    date: '2026-01-20',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=500&fit=crop&q=80',
  },
  {
    id: 3,
    slug: 'ccna-vs-cybersecurity',
    title: 'CCNA vs Cybersecurity',
    category: 'Comparison',
    excerpt: 'Understanding the differences between CCNA and Cybersecurity career paths.',
    author: 'Admin',
    date: '2026-01-25',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop&q=80',
  },
  {
    id: 4,
    slug: 'what-is-ethical-hacking',
    title: 'What is Ethical Hacking?',
    category: 'Ethical Hacking',
    excerpt: 'Explore the world of ethical hacking and how it helps organizations protect their digital assets.',
    author: 'Admin',
    date: '2026-02-01',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=500&fit=crop&q=80',
  },
  {
    id: 5,
    slug: 'networking-fundamentals',
    title: 'Networking Fundamentals',
    category: 'Networking',
    excerpt: 'Master the basics of computer networking including protocols, topologies, and essential concepts.',
    author: 'Admin',
    date: '2026-02-05',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1535276484715-69c2a1c4f03c?w=800&h=500&fit=crop&q=80',
  },
  {
    id: 6,
    slug: 'common-cybersecurity-threats',
    title: 'Common Cybersecurity Threats',
    category: 'Threats',
    excerpt: 'Learn about the most common cybersecurity threats facing organizations today.',
    author: 'Admin',
    date: '2026-02-10',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1505289436230-9c6769b0f73f?w=800&h=500&fit=crop&q=80',
  },
];

export const navLinks = [
  { name: 'Home', href: '/' },
  { name: 'About Us', href: '/about' },
  { name: 'Courses', href: '/courses' },
  { name: 'Gallery', href: '/gallery' },
  { name: 'Blogs', href: '/blogs' },
  { name: 'Contact Us', href: '/contact' },
];

// Add legal pages to your data
export const legalPages = [
  { name: 'Privacy Policy', href: '/privacy-policy' },
  { name: 'Terms & Conditions', href: '/terms' },
  { name: 'Disclaimer', href: '/disclaimer' },
];